repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: mixed-line-ending
  - repo: https://github.com/arduino/clang-format-action
    rev: v3.0.0
    hooks:
      - id: clang-format
        files: "\\.(c|h|cpp|hpp)$"
