// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: sq_ui

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

#include "ui.h"
#include "ui_helpers.h"

#include "can.h"
#include "pwm.h"
#include "rs485.h"
#include "wifi.h"

// EVENTS
lv_obj_t* ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t* ui_imgset_[1] = {&ui_img_485_png};
const lv_img_dsc_t* ui_imgset_wifi_[4] = {&ui_img_wifi_1_png, &ui_img_wifi_2_png, &ui_img_wifi_3_png,
                                          &ui_img_wifi_4_png};

// UI Initialization
void ui_init(void) {
  lv_disp_t* dispp = lv_disp_get_default();
  lv_theme_t* theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                            false, LV_FONT_DEFAULT);
  lv_disp_set_theme(dispp, theme);

  ui_Login_screen_init();
  ui_Create_Uesr_screen_init();
  ui_Main_screen_init();
  ui_Main_RS485_screen_init();
  ui_Main_CAN_screen_init();
  ui_Main_PWM_screen_init();
  ui_Main_WIFI_screen_init();

  ui____initial_actions0 = lv_obj_create(NULL);

  lv_disp_load_scr(ui_Login);
}

#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif
